export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERR = "SIGNUP_ERR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERR = "LOGIN_ERR";

export const USER_SIGNOUT = "USER_SIGNOUT";
export const INPUT_SUMMARIZED = "INPUT_SUMMARIZED";
export const INPUT_CHANGE = "INPUT_CHANGE";